#!/bin/bash

# Setup ROS distro and ROS
curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
apt-get update
apt-get install -f -y
apt-get install -y build-essential \
    cmake \
    gh \
    git \
    python3-colcon-common-extensions \
    python3-pip \
    python3-rosdep \
    python3-vcstool \
    wget

apt-get install -y ros-$ROS_DISTRO-ros-base \
    ros-$ROS_DISTRO-pcl-ros \
    ros-$ROS_DISTRO-teleop-twist-joy \
    ros-$ROS_DISTRO-joy \
    ros-$ROS_DISTRO-vision-opencv \
    ros-$ROS_DISTRO-nav2-behaviors \
    ros-$ROS_DISTRO-nav2-navfn-planner \
    ros-$ROS_DISTRO-nav2-controller \
    ros-$ROS_DISTRO-laser-filters \
    htop can-utils nginx

# clean up to reduce image size
apt-get clean
rm -rf /var/lib/apt/lists/*
